= DocBook ℞
Dan Allen

The prescription (℞) you need to get rid of your DocBook problem.
Extracts AsciiDoc from DocBook XML (hell).

The docbookrx.rb script is the beginnings of a DocBook to http://asciidoc.org[AsciiDoc] converter written in Ruby.
This script is far from perfect at the moment and some of the conversion is done hastily.
The plan is to evolve the script into a robust library for performing this conversion in a reliable way.

== Running the script

To run the script, simply execute it with Ruby and pass a DocBook file as the first argument to convert.

 $ ruby docbookrx.rb sample.xml

The script currently prints the AsciiDoc to stdout.
You need to redirect the output to a file in order to save it.

 $ ruby docbookrx.rb sample.xml > sample.ad

It's not perfect yet, but we'll get there with your help.
You'll find a list of tasks that need attention listed in the WORKLOG.adoc file.

== Authors

*docbookrx* was written by https://github.com/mojavelinux[Dan Allen].

== Copyright

Copyright (C) 2015 Dan Allen.
Free use of this software is granted under the terms of the MIT License.

See the link:LICENSE[LICENSE] file for details.
