= DocBook ℞
Dan Allen <https://github.com/mojavelinux>

The prescription (℞) you need to get rid of your DocBook problem.
Extracts AsciiDoc from DocBook XML (hell).

DocBook ℞ is the beginnings of a DocBook to http://asciidoc.org[AsciiDoc] converter written in Ruby.
This converter is far from perfect at the moment and some of the conversion is done hastily.
The plan is to evolve it into a robust library for performing this conversion in a reliable way.

== Running the converter

To run the converter, you first need to install the dependencies:

 $ bundle
 
Next, execute the launch script and pass a DocBook file to convert as the first argument.

 $ ./bin/docbookrx sample.xml

The script will automatically create the output file [path]_sample.adoc_, replacing the DocBook file extension, `.xml` with the AsciiDoc file extension, `.adoc`.

The converter is not perfect yet, but we'll get there with your help.
You'll can find a list of tasks that need attention listed in the WORKLOG.adoc file.

== Authors

*docbookrx* was written by https://github.com/mojavelinux[Dan Allen].

== Credits

Gem structure originally created using https://github.com/bkuhlmann/gemsmith[Gemsmith].

== Copyright

Copyright (C) 2013-2015 Dan Allen and the Asciidoctor Project.
Free use of this software is granted under the terms of the MIT License.

See the link:LICENSE[LICENSE] file for details.
