= DocBookRx: The ℞ for all your DocBook pain
Dan Allen <https://github.com/mojavelinux>
// Settings:
:idprefix:
:idseparator: -
:icons: font
// Aliases:
:project-name: DocBookRx
:project-handle: docbookrx
// URIs:
:uri-repo: https://github.com/asciidoctor/docbookrx
:uri-asciidoc: http://asciidoc.org
:uri-docbook: http://docbook.org
:uri-rvm: http://rvm.io
:uri-install-rvm: https://rvm.io/rvm/install

The prescription (℞) you need to get rid of your DocBook pain.
Converts from DocBook XML (hell) to AsciiDoc.
//Extracts AsciiDoc from DocBook XML (hell).

{project-name} is the start of a {uri-docbook}[DocBook] to {uri-asciidoc}[AsciiDoc] converter written in Ruby.
This converter is far from perfect at the moment and some of the conversion is done hastily.
The plan is to evolve it into a robust library for performing this conversion in a reliable way.

== Installing the development version

Currently, {project-name} is only available in source form.
You'll need to retrieve the source and run the application out the source directory.

=== Retrieve the source code

Simply copy the {uri-repo}[GitHub repository URL] and pass it to the `git clone` command:

[subs=attributes+]
 $ git clone {uri-repo}

Next, switch to the project directory:

[subs=attributes+]
 $ cd {project-handle}

=== Prepare RVM (optional)

We recommend using {uri-rvm}[RVM] when developing applications with Ruby.
Follow the {uri-install-rvm}[installation instructions] on the RVM site to setup RVM and install Ruby.

Once you have RVM setup, we recommend creating a new gemset to work with {project-name}:

[subs=attributes+]
 $ rvm use default@{project-handle}-dev --create

We like RVM because it keeps the dependencies required by various projects isolated from each other and from your system.

=== Install the dependencies

The dependencies needed to use {project-name} are defined in the [path]_Gemfile_ at the root of the project.
You'll use Bundler to install these dependencies.

To check if you have Bundler available, use the `bundle` command to query the version installed:

 $ bundle --version

If it's not installed, use the `gem` command to install it.

 $ gem install bundler

Then, use the `bundle` command (which is provided by the bundler gem) to install the project dependencies:

 $ bundle

NOTE: You must invoke `bundle` from the project's root directory so it can locate the [path]_Gemfile_.

== Running the converter

To run the converter, execute the launch script and pass a DocBook file to convert as the first argument.

 $ ./bin/docbookrx sample.xml

The script will automatically create the output file [path]_sample.adoc_, replacing the DocBook file extension, `.xml` with the AsciiDoc file extension, `.adoc`.

The converter is not perfect yet, but we'll get there with your help.
You'll can find a list of tasks that need attention listed in the WORKLOG.adoc file.

== Authors

*docbookrx* was written by https://github.com/mojavelinux[Dan Allen].

== Credits

Gem structure originally created using https://github.com/bkuhlmann/gemsmith[Gemsmith].

== Copyright

Copyright (C) 2013-2015 Dan Allen and the Asciidoctor Project.
Free use of this software is granted under the terms of the MIT License.

See the link:LICENSE[LICENSE] file for details.
